import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("content CSS scopes styles and fixes panel dimensions", () => {
  const css = readFileSync("src/content/content.css", "utf8");

  assert.match(css, /#todo-extension-root/);
  assert.match(css, /\.todo-panel[\s\S]*width:\s*380px/);
  assert.match(css, /\.todo-panel[\s\S]*max-height:\s*560px/);
  assert.match(css, /\.todo-panel[\s\S]*width:\s*min\(380px,\s*calc\(100vw\s*-\s*24px\)\)/);
  assert.match(css, /\.todo-panel[\s\S]*max-height:\s*min\(560px,\s*calc\(100vh\s*-\s*24px\)\)/);
  assert.match(css, /\.todo-panel[\s\S]*position:\s*fixed/);
  assert.doesNotMatch(css, /\.todo-panel[\s\S]*bottom:\s*60px/);
  assert.match(css, /\.todo-shell[\s\S]*right:\s*0/);
  assert.match(css, /\.todo-shell[\s\S]*--todo-ball-size:\s*44px/);
  assert.match(css, /--todo-ball-aqua:\s*#78d9dd/i);
  assert.match(css, /--todo-ball-orange:\s*#ff8a1f/i);
  assert.match(css, /--todo-ball-ink:\s*#071833/i);
  assert.match(css, /\.todo-ball[\s\S]*width:\s*var\(--todo-ball-size\)/);
  const ballRule = cssRule(css, "#todo-extension-root .todo-ball");
  assert.match(ballRule, /background:\s*#ffffff/i);
  assert.match(css, /\.todo-ball::before/);
  const ballInnerRule = cssRule(css, "#todo-extension-root .todo-ball::before");
  assert.match(ballInnerRule, /inset:\s*calc\(var\(--todo-ball-size\)\s*\*\s*0\.08\)/i);
  assert.match(ballInnerRule, /border-radius:\s*999px/i);
  assert.match(css, /\.todo-ball-count[\s\S]*background:\s*#ffffff/i);
  assert.match(css, /\.todo-ball-count[\s\S]*color:\s*var\(--todo-ball-ink\)/i);
  assert.doesNotMatch(css, /\.todo-ball-badge/);
  const ballTimerActiveRule = cssRule(css, "#todo-extension-root .todo-ball--timer-active");
  assert.match(ballTimerActiveRule, /--todo-ball-progress:\s*0deg/i);
  assert.match(ballTimerActiveRule, /--todo-ball-progress-color:\s*var\(--todo-ball-theme\)/i);
  assert.match(ballTimerActiveRule, /conic-gradient\(\s*var\(--todo-ball-progress-color\)\s+var\(--todo-ball-progress\)/i);
  const ballTimerPausedRule = cssRule(css, "#todo-extension-root .todo-ball--timer-paused");
  assert.match(ballTimerPausedRule, /filter:\s*saturate\(0\.72\)/i);
  const ballTimerToggleRule = cssRule(css, "#todo-extension-root .todo-ball-timer-toggle");
  assert.match(ballTimerToggleRule, /bottom:\s*calc\(var\(--todo-ball-size\)\s*\*\s*0\.08\)/);
  assert.match(ballTimerToggleRule, /width:\s*calc\(var\(--todo-ball-size\)\s*\*\s*0\.34\)/);
  assert.doesNotMatch(ballTimerToggleRule, /inset:/);
  const ballTimerValueRule = cssRule(css, "#todo-extension-root .todo-ball-timer-value");
  assert.match(ballTimerValueRule, /max-width:\s*calc\(var\(--todo-ball-size\)\s*\*\s*0\.82\)/);
  assert.match(ballTimerValueRule, /font-size:\s*calc\(var\(--todo-ball-size\)\s*\*\s*0\.2\)/);
  assert.match(ballTimerValueRule, /pointer-events:\s*none/);
  assert.doesNotMatch(ballTimerValueRule, /text-overflow:\s*ellipsis/);
  assert.match(css, /\.todo-panel-header[\s\S]*height:\s*52px/);
  assert.match(css, /\.todo-create-form[\s\S]*min-height:\s*58px/);
  assert.match(css, /\.todo-item::before[\s\S]*left:\s*0[\s\S]*width:\s*3px/);
  assert.match(css, /\.todo-item-actions button[\s\S]*border:\s*0/);
  assert.match(css, /\.todo-header-settings:focus-visible[\s\S]*outline:\s*3px solid #0f172a/i);
  assert.match(css, /\.todo-icon[\s\S]*width:\s*17px/);
  assert.match(css, /\.todo-item-main[\s\S]*display:\s*grid/);
  assert.match(css, /\.todo-item-title-row[\s\S]*display:\s*grid/);
  assert.match(css, /\.todo-item-footer[\s\S]*justify-content:\s*space-between/);
  assert.match(css, /\.todo-text,[\s\S]*\.todo-title-link[\s\S]*text-overflow:\s*ellipsis/);
  assert.match(css, /\.todo-text,[\s\S]*\.todo-title-link[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.todo-title-link\s*\{[\s\S]*color:\s*var\(--todo-cobalt\)/);
  assert.match(css, /\.todo-title-link\s*\{[\s\S]*text-decoration:\s*underline/);
  assert.match(css, /\.todo-title-link\s*\{[\s\S]*background:\s*color-mix\(in srgb,\s*var\(--todo-cobalt\)\s*8%,\s*transparent\)/);
  assert.match(css, /\.todo-text[\s\S]*font:\s*800 14px\/1\.45 Arial,\s*sans-serif/);
  assert.doesNotMatch(css, /todo-task-check/);
  assert.match(css, /\.todo-create-control:focus-within/);
  assert.match(css, /\.todo-ball:focus-visible\s*\{[\s\S]*outline:\s*3px solid #0f172a[\s\S]*outline-offset:\s*4px/i);
  assert.match(css, /\.todo-ball:focus-visible\s*\{[\s\S]*box-shadow:\s*0 0 0 2px #fff,\s*0 0 0 5px #0f172a/i);
  assert.match(css, /\.todo-create-form\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto/);
  assert.match(css, /\.todo-create-link-control[\s\S]*grid-column:\s*1\s*\/\s*-1/);
  assert.match(css, /\.todo-create-link-input[\s\S]*font:\s*14px\/1\.35 Arial,\s*sans-serif/);
  assert.match(css, /\.todo-list\s*\{[\s\S]*padding:\s*12px\s+16px\s+14px/);
  assert.match(css, /\.todo-create-submit:focus-visible\s*\{[\s\S]*outline:\s*3px solid #0f172a/i);
  assert.match(css, /\.todo-create-preview[\s\S]*grid-column:\s*1\s*\/\s*-1/);
  assert.match(css, /\.todo-create-preview\[hidden\][\s\S]*display:\s*none/);
  assert.match(css, /\.todo-created-at,[\s\S]*\.todo-reminder-chip[\s\S]*text-overflow:\s*ellipsis/);
  assert.match(css, /\.todo-meta-separator[\s\S]*color:\s*#cbd5e1/i);
  assert.match(css, /\.todo-toast--reminder[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto/);
  assert.match(css, /\.todo-toast-ack[\s\S]*border:\s*0/);
  assert.equal(css.includes("body {"), false);
});

function cssRule(css, selector) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = css.match(new RegExp(`${escapedSelector}\\s*\\{([\\s\\S]*?)\\}`));
  return match?.[1] || "";
}
